/**
 * Shared TypeScript types for the LCC frontend.
 * These mirror the Pydantic schemas from the backend.
 */

// ── Health & Connection ──

export interface HealthResponse {
  status: 'ok' | 'degraded' | 'error';
  app_name: string;
  app_version: string;
  lemonade_url: string;
  lemonade_reachable: boolean;
  lemonade_version: string | null;
}

export type ConnectionStatus = 'connected' | 'degraded' | 'disconnected' | 'checking';

// ── Capabilities ──

export interface Capabilities {
  health: boolean;
  stats: boolean;
  system_info: boolean;
  load: boolean;
  unload: boolean;
  delete: boolean;
  delete_enabled: boolean;
  pull: boolean;
  internal_config: boolean;
  internal_set: boolean;
  ollama_tags: boolean;
  ollama_ps: boolean;
  ollama_show: boolean;
  ollama_version: boolean;
  openai_models: boolean;
  websocket: boolean;
  websocket_port: number | null;
  cmd_systemctl: boolean;
  cmd_journalctl: boolean;
  cmd_sensors: boolean;
  restart_enabled: boolean;
  lemonade_version: string | null;
  probe_timestamp: string | null;
}

// ── Navigation ──

export interface NavItem {
  href: string;
  label: string;
  icon: string;
  milestone: string;
  requiresCapability?: keyof Capabilities;
}

// ── Lemonade Health (from /api/lemonade/health) ──

export interface LemonadeHealth {
  raw: Record<string, unknown>;
  version: string | null;
  status: string;
  loaded_models: Record<string, unknown>[];
  websocket_port: number | null;
}

// ── Hardware ──

export interface HardwareInfo {
  ram_total_gb: number;
  ram_used_gb: number;
  ram_available_gb: number;
  ram_percent: number;
  swap_total_gb: number;
  swap_used_gb: number;
  cpu_percent: number;
  cpu_count: number;
  disk_total_gb: number | null;
  disk_used_gb: number | null;
  disk_free_gb: number | null;
  disk_percent: number | null;
  disk_path: string | null;
}

// ═══════════════════════════════════════════════
// Dashboard Types (M4)
// ═══════════════════════════════════════════════

/** Aggregated dashboard data from multiple endpoints. */
export interface DashboardData {
  serverStatus: ServerStatus | null;
  loadedModel: LoadedModelInfo | null;
  lastTask: LastTaskInfo | null;
  hardware: HardwareInfo | null;
  alerts: SmartAlert[];
  timestamp: Date;
}

export interface ServerStatus {
  status: 'running' | 'stopped' | 'error' | 'unknown';
  version: string | null;
  apiPort: number;
  websocketPort: number | null;
  globalTimeout: number | null;
  maxLoadedModels: number | null;
  defaultBackend: string | null;
}

export interface LoadedModelInfo {
  name: string;
  backend: string | null;
  ctxSize: number | null;
  ngl: number | null;
  mmap: boolean | null;
  jinja: boolean;
  specType: string | null;
  specDraftMax: number | null;
  reasoningFormat: string | null;
  mmproj: string | null;
  pid: number | null;
  rssGb: number | null;
  cpuPercent: number | null;
  uptime: string | null;
  uptimeSeconds: number | null;
}

export interface LastTaskInfo {
  available: boolean;
  inputTokens: number | null;
  outputTokens: number | null;
  promptEvalTps: number | null;
  generationTps: number | null;
  ttftSeconds: number | null;
  totalDurationSeconds: number | null;
  finishReason: string | null;
  finishConfidence: 'confirmed' | 'inferred' | 'unknown';
  finishEvidence: string | null;
}

/** Smart alert generated by the dashboard alert engine. */
export interface SmartAlert {
  id: string;
  level: 'warning' | 'error' | 'info';
  title: string;
  description: string;
  suggestion: string;
  icon: string;
}

export type DashboardLoadingState = 'loading' | 'loaded' | 'error' | 'partial';

// ═══════════════════════════════════════════════
// Models Types (M5)
// ═══════════════════════════════════════════════

export interface ModelEntry {
  name: string;
  model: string | null;
  size: number | null;
  sizeFormatted: string;
  digest: string | null;
  modifiedAt: string | null;
  details: Record<string, unknown> | null;
  isLoaded: boolean;
}

export interface RuntimeParams {
  executable: string | null;
  modelPath: string | null;
  ctxSize: number | null;
  port: number | null;
  host: string | null;
  ngl: number | null;
  backend: string | null;
  mmap: boolean | null;
  jinja: boolean;
  mmproj: string | null;
  contextShift: boolean | null;
  keep: number | null;
  reasoningFormat: string | null;
  specType: string | null;
  specDraftMax: number | null;
  specDraftPMin: number | null;
  rawCmdline: string;
}

export interface LoadedModelDetail {
  name: string;
  params: RuntimeParams | null;
  process: {
    pid: number;
    rssGb: number;
    cpuPercent: number;
    uptime: string;
    uptimeSeconds: number;
  } | null;
}

export interface LoadModelOptions {
  modelName: string;
  ctxSize: number | null;
  llamacppBackend: string | null;
  llamacppArgs: string;
  saveOptions: boolean;
}

export interface ActionState {
  loading: boolean;
  error: string | null;
}

// ═══════════════════════════════════════════════
// Notification Types (M9)
// ═══════════════════════════════════════════════

export type NotificationLevel = 'success' | 'error' | 'warning' | 'info';

export interface Notification {
  id: string;
  level: NotificationLevel;
  title: string;
  message: string;
  timestamp: Date;
  read: boolean;
  href: string | null;
  toastDuration: number;
}

export interface ToastData {
  id: string;
  level: NotificationLevel;
  title: string;
  message: string;
  duration: number;
  exiting: boolean;
}

// ═══════════════════════════════════════════════
// Profile Types (M10)
// ═══════════════════════════════════════════════

export interface ProfileConfig {
  ctx_size: number | null;
  global_timeout: number | null;
  llamacpp_backend: string | null;
  llamacpp_args: string | null;
  max_tokens: number | null;
  temperature: number | null;
  app_timeout: number | null;
  stop_sequences: string | null;
}

export interface Profile {
  id: string;
  name: string;
  description: string;
  icon: string;
  config: ProfileConfig;
  is_builtin: boolean;
  is_default: boolean;
  created_at: string;
  updated_at: string;
}

export interface ModelProfiles {
  model_name: string;
  default_profile_id: string | null;
  profiles: Profile[];
}

export interface SmartRecommendation {
  model_name: string;
  model_size_gb: number | null;
  ram_total_gb: number;
  ram_available_gb: number;
  recommended_ctx: number;
  safe_max_ctx: number;
  risk_threshold_ctx: number;
  warnings: string[];
  notes: string[];
}
